### ISSUE TITLE
Minify size of module size

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/react-crudeditor#35]
On current version if we create a single editor and then minify it (without react and react dom) bundle is about 1.5 MB size.

**Comment by estambakio-sc** [comment]
We removed @opuscapita/i18n in #38 and with the following webpack plugins

```
const webpack = require('webpack');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const LodashModuleReplacementPlugin = require('lodash-webpack-plugin');

...

plugins: [
    new webpack.optimize.ModuleConcatenationPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('production')
    }),
    new UglifyJsPlugin(),
    new BundleAnalyzerPlugin(),
    new LodashModuleReplacementPlugin(),
    new webpack.LoaderOptionsPlugin({
      minimize: true
    })
  ]
```

we build a 830 kB bundle. 

The bundle structure according to BundleAnalyzerPlugin:

![crud-bundle-structure](https://user-images.githubusercontent.com/31243790/33004716-6fff06e6-cdd3-11e7-831a-0671e799617a.png)

**Comment by amourzenkov-sc** [comment]
Suggestion by @dzhitomirsky-sc : move "@opuscapita/react-dates" to **peerDependencies**

**Comment by estambakio-sc** [comment]
It should be discussed with @asergeev-sc , because currently we provide `date` component as a core feature of crudEditor and this is not obvious if we can move `react-dates` to peerDependencies or not. 

One thing we can do (in `react-dates` itself) is strip off not used locales with this webpack plugin: 

```
new webpack.ContextReplacementPlugin(
  /moment[\/\\]locale$/,
  /en|de|fi|ru|no|sv/
)
```
which results in 660kB build instead of 965kB, which is **~300kB saving** not minified. It also requires approval by @asergeev-sc.

I'm also thinking about creating some sort of plugin system for crudEditor, so that it could be extensible by developers. In such case we could split `date` types, components, etc. into a plugin. For editors which don't need dates this could result in ~50% smaller bundle.

**Comment by estambakio-sc** [comment]
According to @asergeev-sc : we need to revision bundling process in order to not include any dependencies into a bundle.

**Comment by estambakio-sc** [comment]
Closing, because module is built and shipped without any dependencies, and there is no potential minification to be done in future.
